import { cn } from "@/lib/utils";
import "../styles/globals.css";
import { Inter } from "next/font/google";
import Provider from "../components/Providers";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/Toast";
import MobileMenu from "@/components/MobileMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn("bg-white text-slate-900 antialiased", inter.className)}
    >
      <body className="min-h-screen bg-slate-50 dark:bg-slate-900 antialiased">
        <Provider>
          {/* @ts-expect-error Server Component */}
          <Navbar />
          <Toaster position="bottom-right" />
          <MobileMenu />
          <main>{children}</main>
        </Provider>
        <div className="h-40 mid:hidden"></div>
      </body>
    </html>
  );
}
